title = "COMP3601 21T3 | Team Orange"
languageCode = "en-au"

relativeURLs = true
theme = "reveal-hugo"

[params]
colouriseSections = true

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[markup.highlight]
codeFences = false

[params.reveal_hugo]
slide_number = true
history = true
center = false
pdf_separate_fragments = false
custom_css = "custom.css"