name: deploy hugo to github pages

on:
  push:
    branches:
    - master
    paths:
    - docs/slides/**
    - docs/.hugo/**

jobs:
  build-deploy:
    if: github.repository != 'featherbear/Slides-Hugo-Template'
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.4.13
      with:
        hugo-version: '0.68.3'
        extended: true

    - name: Build
      run: cd docs/.hugo && hugo --gc --minify --cleanDestinationDir -d public

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.3.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs/.hugo/public
