name: deploy hugo to github pages

on:
  push:
    branches:
    - master
    paths:
    - docs/slides/**
    - docs/.hugo/**
    - docs/.meeting_logs/**

jobs:
  build-deploy:
    if: github.repository != 'featherbear/Slides-Hugo-Template'
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.4.13
      with:
        hugo-version: '0.68.3'
        extended: true

    - name: Build slides
      run: hugo --gc --minify --cleanDestinationDir -d ../www_public
      working-directory: ./docs/.hugo

    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Build meeting logs site
      run: |
        npm install
        npm run build
        cp -R public ../www_public/meetings
      working-directory: ./docs/.meeting_logs

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.3.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs/www_public
